### PR TITLE
chore: release v1.1.1

### PR DESCRIPTION
**Pull request by c12i**
## 🤖 New release
* `mpesa`: 1.1.0 -> 1.1.1

<details><summary><i><b>Changelog</b></i></summary><p>

<blockquote>

### Fixed
- fix spelling
- fix formatting

### Other
- Merge pull request [#104](https://github.com/collinsmuriuki/mpesa-rust/pull/104) from c12i/chore/update-mpesa-variables
- follow API variable naming as per Daraja
- move express-request and transaction reversal to builder pattern ([#88](https://github.com/collinsmuriuki/mpesa-rust/pull/88))
- Add discord badge
- Merge pull request [#95](https://github.com/collinsmuriuki/mpesa-rust/pull/95) from Tevinthuku/improvements-and-less-noise
- static lifetime for request path
- remove unneeded lifetime
- refactor impl of getting the pass
- remove unused imports
- Add module level docs
- Update dynamic qr code setter and request amount field's type to u32
- Update twitter url
- Remove nextest config
- Simplify readme table
- Update readme
- Add no_run marker to c2b register
- Add main function to bill manager docs code snippets
- Move bill manager docs to md
- Remove unnecessary lazy evaluations
- Fix readme failing doc test
- Update docs
- Fix typo in docs
- Enable doc tests in readme
- Fix clippy warnings
- Further fix code snippet indentation in docs
- Only have core apis in doc tests
- Add editor config, fix indentation inconsistencies in docs
- Fix transaction reversal api 400 errors
- Fix dynamic qr code doc tests
- Update transaction apis docs
- Fix env vars not read in doc tests
- Enable and move doc tests to markdown files
- *(client)* Generic `send` implementation ([#89](https://github.com/collinsmuriuki/mpesa-rust/pull/89))
</blockquote>

</p></details>

---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).

### CODE REVIEW

**Review by itsyaasir — APPROVED** [review]

**Comment by c12i** [comment]
I am seeing that #88 is a breaking change that should not be part of this release, this warrants a major version bump

**Comment by itsyaasir** [comment]
Yeah, this was old PR so I forgot to follow the commit standards.

Plus I think the release-plz configuration is not fully configured.

**Comment by c12i** [comment]
What configs would you recommend overriding

https://release-plz.ieni.dev/docs/config

**Comment by c12i** [comment]
closing this PR for now since I have removed the breaking changes from the `v1` maintenance branch

**Pull request closed without merging**
